### ISSUE TITLE
AttributeError: type object 'Qt' has no attribute 'MarkdownText'

### ISSUE THREAD

**Issue by davidenitti** [Rolf-Hempel/PlanetarySystemStacker#38]
I installed the program on linux with
`sudo pip3 install planetary-system-stacker`
but when I run PlanetarySystemStacker I get
```
20-11-31.1 Info: libmkl_rt.so not found (Intel Math Kernel Library not installed?). Performance might be slightly reduced.

Traceback (most recent call last):
  File "/usr/local/bin/PlanetarySystemStacker", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/planetary_system_stacker/planetary_system_stacker.py", line 1469, in main
    myapp = PlanetarySystemStacker()
  File "/usr/local/lib/python3.8/dist-packages/planetary_system_stacker/planetary_system_stacker.py", line 322, in __init__
    self.display_widget(DisplayQuickstart(self, self.configuration))
  File "/usr/local/lib/python3.8/dist-packages/planetary_system_stacker/display_quickstart.py", line 46, in __init__
    self.label.setTextFormat(Qt.MarkdownText)
AttributeError: type object 'Qt' has no attribute 'MarkdownText'
```

**Comment by alexjarosch** [comment]
Hi David,
Could you provide us with a list of what is installed in your pip environment, say with:
```pip3 list```
and tell us what version of python you use?

To avoid cross-conflicts with your system python installation, did you try to install it in an virtual environment?
Go to a folder where you want to install PSS and then:
``` 
python -m venv pss-dev
source pss-dev/bin/activate
pip3 install planetary-system-stacker
```
Cheers,
Alex

**Comment by davidenitti** [comment]
I have python3.8, I'll try the virtual env.
pip3 list gives:
```
absl-py                  0.10.0              
addict                   2.3.0               
aiodns                   2.0.0               
aiohttp                  3.7.3               
apturl                   0.5.2               
astroalign               2.1                 
astropy                  4.1                 
astunparse               1.6.3               
async-timeout            3.0.1               
atomicwrites             1.1.5               
attrs                    19.3.0              
bcrypt                   3.1.7               
bintrees                 2.0.7               
BitstampClient           2.2.8               
blinker                  1.4                 
Brlapi                   0.7.0               
cachetools               4.1.1               
ccxt                     1.39.52             
certifi                  2020.6.20           
cexapi                   0.1                 
chardet                  3.0.4               
Click                    7.0                 
colorama                 0.4.3               
command-not-found        0.3                 
configobj                5.0.6               
cryptography             2.8                 
cupshelpers              1.0                 
cycler                   0.10.0              
dbus-python              1.2.16              
decorator                4.4.2               
defer                    1.0.6               
Deprecated               1.2.10              
distro                   1.4.0               
distro-info              0.23ubuntu1         
duplicity                0.8.12.0            
entrypoints              0.3                 
ephem                    3.7.7.1             
ExifRead                 2.1.2               
fasteners                0.14.1              
forex-python             1.5                 
fsspec                   0.8.4               
future                   0.18.2              
gast                     0.3.3               
gdax                     1.0.6               
glob2                    0.7                 
google-auth              1.22.1              
google-auth-oauthlib     0.4.1               
google-pasta             0.2.0               
grpcio                   1.33.1              
h5py                     2.10.0              
httplib2                 0.14.0              
hypothesis               4.36.2              
idna                     2.8                 
imageio                  2.9.0               
imgaug                   0.4.0               
importlib-metadata       1.5.0               
imreg-dft                2.0.0               
intel-openmp             2021.1.2            
IPTCInfo3                2.1.4               
joblib                   0.17.0              
Keras-Preprocessing      1.1.2               
keyring                  18.0.1              
kiwisolver               1.2.0               
krakenex                 2.1.0               
language-selector        0.1                 
launchpadlib             1.10.13             
lazr.restfulclient       0.14.2              
lazr.uri                 1.0.3               
llvmlite                 0.34.0              
lmdb                     1.0.0               
lockfile                 0.12.2              
louis                    3.12.0              
macaroonbakery           1.3.1               
Mako                     1.1.0               
Markdown                 3.3.3               
MarkupSafe               1.1.0               
matplotlib               3.3.2               
meld                     3.20.2              
memory-profiler          0.58.0              
mkl                      2021.1.1            
mmcv                     1.1.5               
monotonic                1.5                 
montage-wrapper          0.9.9               
MontagePy                1.0.1               
more-itertools           4.2.0               
multidict                5.1.0               
netifaces                0.10.4              
networkx                 2.5                 
numba                    0.51.2              
numpy                    1.18.5              
oauthlib                 3.1.0               
olefile                  0.46                
opencv-python            4.4.0.44            
opencv-python-headless   4.5.1.48            
opt-einsum               3.3.0               
packaging                20.3                
pandas                   1.1.4               
paramiko                 2.6.0               
pexpect                  4.6.0               
Pillow                   8.0.1               
pip                      20.0.2              
planetary-system-stacker 0.8.30.22           
pluggy                   0.13.0              
ply                      3.11                
protobuf                 3.14.0              
psutil                   5.7.3               
py                       1.8.1               
py3exiv2                 0.8.0               
pyasn1                   0.4.8               
pyasn1-modules           0.2.8               
pycairo                  1.16.2              
pycares                  3.1.1               
pycparser                2.20                
pycups                   1.9.73              
pycurl                   7.43.0.2            
PyExifTool               0.1.1               
pyexiv2                  2.3.1               
PyGObject                3.36.0              
PyJWT                    1.7.1               
pymacaroons              0.13.0              
PyNaCl                   1.3.0               
pyparsing                2.4.7               
pyplate                  3.1.0               
PyQt5                    5.15.2              
PyQt5-sip                12.8.1              
PyQt5-stubs              5.14.2.2            
pyRFC3339                1.1                 
pytest                   4.6.9               
pytest-arraydiff         0.3                 
pytest-astropy           0.7.0               
pytest-astropy-header    0.1.2               
pytest-doctestplus       0.5.0               
pytest-openfiles         0.4.0               
pytest-remotedata        0.3.2               
python-apt               2.0.0+ubuntu0.20.4.3
python-bitbay            0.1.2               
python-dateutil          2.7.3               
python-debian            0.1.36ubuntu1       
pytimeparse              1.1.8               
pytorch-lightning        1.0.8               
pytorch-msssim           0.2.1               
pytz                     2019.3              
PyWavelets               1.1.1               
pyxattr                  0.6.1               
pyxdg                    0.26                
PyYAML                   5.3.1               
rawkit                   0.6.0               
rawpy                    0.15.0              
reportlab                3.5.34              
requests                 2.25.1              
requests-oauthlib        1.3.0               
requests-unixsocket      0.2.0               
rsa                      4.6                 
scikit-image             0.17.2              
scikit-learn             0.23.2              
scipy                    1.5.3               
scour                    0.37                
screen-resolution-extra  0.0.0               
SecretStorage            2.3.1               
selenium                 3.141.0             
sep                      1.0.3               
setuptools               45.2.0              
Shapely                  1.7.1               
simplejson               3.16.0              
sip                      4.19.21             
six                      1.10.0              
sklearn                  0.0                 
systemd-python           234                 
tbb                      2021.1.1            
tensorboard              2.4.0               
tensorboard-plugin-wit   1.7.0               
tensorflow               2.3.1               
tensorflow-estimator     2.3.0               
termcolor                1.1.0               
test-tube                0.7.5               
threadpoolctl            2.1.0               
tifffile                 2020.10.1           
torch                    1.6.0               
torchgeometry            0.1.2               
torchsampler             0.1                 
torchvision              0.7.0               
tqdm                     4.51.0              
typing-extensions        3.7.4.3             
ubuntu-advantage-tools   20.3                
ubuntu-drivers-common    0.0.0               
ufw                      0.36                
unattended-upgrades      0.1                 
unicodecsv               0.14.1              
Unidecode                1.1.1               
urllib3                  1.25.8              
usb-creator              0.3.7               
vboxapi                  1.0                 
wadllib                  1.3.3               
wcwidth                  0.1.8               
websocket-client         0.40.0              
Werkzeug                 1.0.1               
wheel                    0.34.2              
wrapt                    1.12.1              
xkit                     0.0.0               
yapf                     0.30.0              
yarl                     1.1.0               
youtube-dl               2020.3.24           
zipp                     1.0.0     
```

**Comment by davidenitti** [comment]
problem fixed, there was an old PyQt5 installation that was causing issues.
thanks for the help!

**Comment by alexjarosch** [comment]
Great that you found the issue, glad to have helped a bit. Enjoy PSS.
Cheers,
Alex
