### ISSUE TITLE
PSS failing. Not sure why

### ISSUE THREAD

**Issue by stevecoh1** [Rolf-Hempel/PlanetarySystemStacker#51]
This was my first attempt at using PSS. I am trying to stack a bunch of images of Saturn, in the form of .fits files that were taken the other night with my Celestron 4se telescope, a Svbony-3o5 camera, using Ccdciel on a Raspberry pi. This resulted in three series of fits files, each 4.2MB.
I tried running them through PSS and it produced the following errors:

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
******************************************************************************
11-08-13.7 Start processing /home/scohen/captures/ccdciel/20220617/Saturn/0152
           Software version used: PlanetarySystemStacker 0.9.1
******************************************************************************
11-08-13.7 +++ Start reading frames +++
11-08-13.7 +++ Start ranking frames +++
/home/scohen/.local/lib/python3.10/site-packages/planetary_system_stacker/rank_frames.py:143: RuntimeWarning: invalid value encountered in true_divide
  self.frame_ranks_original /= self.frame_ranks_max_value_original
11-08-14.0 +++ Initializing frame alignment +++
11-08-14.0 +++ Start aligning all frames +++
11-08-14.0 Warning: No valid shift computed at frame 1, will try another stabilization patch
           Next alignment rectangle tried: 696<y<1023, 950<x<1554
11-08-14.0 Warning: No valid shift computed at frame 1, will try another stabilization patch
           Next alignment rectangle tried: 696<y<1023, 648<x<1252
11-08-14.0 Warning: No valid shift computed at frame 1, will try another stabilization patch
           Next alignment rectangle tried: 696<y<1023, 346<x<950
11-08-14.1 Warning: No valid shift computed at frame 1, will try another stabilization patch
           Next alignment rectangle tried: 696<y<1023, 44<x<648
11-08-14.1 Warning: No valid shift computed at frame 1, will try another stabilization patch
           Next alignment rectangle tried: 533<y<860, 1252<x<1856
11-08-14.1 Warning: No valid shift computed at frame 1, will try another stabilization patch
           Next alignment rectangle tried: 533<y<860, 950<x<1554
11-08-14.1 Warning: No valid shift computed at frame 1, will try another stabilization patch
           Next alignment rectangle tried: 533<y<860, 648<x<1252
11-08-14.1 Warning: No valid shift computed at frame 1, will try another stabilization patch
           Next alignment rectangle tried: 533<y<860, 346<x<950
11-08-14.1 Warning: No valid shift computed at frame 1, will try another stabilization patch
           Next alignment rectangle tried: 533<y<860, 44<x<648
11-08-14.1 Warning: No valid shift computed at frame 1, will try another stabilization patch
           Next alignment rectangle tried: 370<y<697, 1252<x<1856
11-08-14.1 Warning: No valid shift computed at frame 1, will try another stabilization patch
           Next alignment rectangle tried: 370<y<697, 950<x<1554
11-08-14.1 Warning: No valid shift computed at frame 1, will try another stabilization patch
           Next alignment rectangle tried: 370<y<697, 648<x<1252
11-08-14.1 Warning: No valid shift computed at frame 1, will try another stabilization patch
           Next alignment rectangle tried: 370<y<697, 346<x<950
11-08-14.2 +++ Start computing the reference frame +++
Traceback (most recent call last):
  File "/home/scohen/.local/lib/python3.10/site-packages/planetary_system_stacker/workflow.py", line 656, in execute_align_frames
    self.align_frames.average_frame()
  File "/home/scohen/.local/lib/python3.10/site-packages/planetary_system_stacker/align_frames.py", line 505, in average_frame
    self.rank_frames.find_best_frames(self.average_frame_number, window_size)
  File "/home/scohen/.local/lib/python3.10/site-packages/planetary_system_stacker/rank_frames.py", line 246, in find_best_frames
    cog_mean_frame = round(100 * mean(best_indices) / self.number, 1)
  File "/usr/lib/python3.10/statistics.py", line 328, in mean
    raise StatisticsError('mean requires at least one data point')
statistics.StatisticsError: mean requires at least one data point
```
I'm not sure what any of this means. It's quite possible I did something wrong in the capturing, but the files all do contain some rather low quality and small images of Saturn. Without sending you the massive amount of data (I can, if you like), I wonder if you could tell me what these messages indicate. Is it possible that these alignment rectangles are missing the small image?

Thank you for all you've done here.

**Comment by stevecoh1** [comment]
Please ignore the above. Silly me, RTFM. I thought I could process individual still images in series. But it seems that movie files are required. Is that right?

**Comment by Rolf-Hempel** [comment]
That's right! Does it work if you click this option?

**Comment by Rolf-Hempel** [comment]
I guess the „Planetary“ option solved your problem. If not, please re-open the issue.
