### ISSUE TITLE
Install fails on Linux Mint

### ISSUE THREAD

**Issue by NorthBaandee** [Rolf-Hempel/PlanetarySystemStacker#64]
Here is the output of pip3 install planetary-system-stacker:
Collecting planetary-system-stacker
  Downloading planetary_system_stacker-0.9.5.2-py3-none-manylinux1_x86_64.whl (232 kB)
     |████████████████████████████████| 232 kB 1.3 MB/s 
Requirement already satisfied: psutil in /usr/lib/python3/dist-packages (from planetary-system-stacker) (5.5.1)
Requirement already satisfied: numpy<1.23.0 in /usr/lib/python3/dist-packages (from planetary-system-stacker) (1.17.4)
Collecting opencv-python-headless
  Downloading opencv_python_headless-4.7.0.72-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (49.2 MB)
     |████████████████████████████████| 49.2 MB 147 kB/s 
Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (from planetary-system-stacker) (1.3.3)
Collecting PyQt5>=5.15
  Downloading PyQt5-5.15.9.tar.gz (3.2 MB)
     |████████████████████████████████| 3.2 MB 1.3 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /tmp/tmpki_n2n3d prepare_metadata_for_build_wheel /tmp/tmpj_uff1pb
         cwd: /tmp/pip-install-_djf6nhp/PyQt5
    Complete output (31 lines):
    Traceback (most recent call last):
      File "/tmp/tmpki_n2n3d", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/tmpki_n2n3d", line 280, in <module>
        main()
      File "/tmp/tmpki_n2n3d", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmpki_n2n3d", line 130, in prepare_metadata_for_build_wheel
        return _get_wheel_metadata_from_wheel(backend, metadata_directory,
      File "/tmp/tmpki_n2n3d", line 159, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/tmp/pip-build-env-ro96h76p/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 46, in build_wheel
        project = AbstractProject.bootstrap('wheel',
      File "/tmp/pip-build-env-ro96h76p/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/tmp/pip-build-env-ro96h76p/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 585, in setup
        self.apply_user_defaults(tool)
      File "/tmp/pip-install-_djf6nhp/PyQt5/project.py", line 68, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-ro96h76p/overlay/lib/python3.8/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-ro96h76p/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/tmp/pip-build-env-ro96h76p/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpki_n2n3d prepare_metadata_for_build_wheel /tmp/tmpj_uff1pb Check the logs for full command output.

**Comment by NorthBaandee** [comment]
Updating pip solved the problem
