### ISSUE TITLE
Error running on Fedora 38

### ISSUE THREAD

**Issue by acostagalex** [Rolf-Hempel/PlanetarySystemStacker#67]
Hi

After update to Fedora 38, have a python version issue

[alex@felapk ~]$ PlanetarySystemStacker
/usr/lib64/python3.11/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.25.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "/home/alex/.local/bin/PlanetarySystemStacker", line 5, in <module>
    from planetary_system_stacker.planetary_system_stacker import main
  File "/home/alex/.local/lib/python3.11/site-packages/planetary_system_stacker/planetary_system_stacker.py", line 64, in <module>
    from workflow import Workflow
  File "/home/alex/.local/lib/python3.11/site-packages/planetary_system_stacker/workflow.py", line 40, in <module>
    from stack_frames import StackFrames
  File "/home/alex/.local/lib/python3.11/site-packages/planetary_system_stacker/stack_frames.py", line 33, in <module>
    from numpy import int as np_int
ImportError: cannot import name 'int' from 'numpy' (/home/alex/.local/lib/python3.11/site-packages/numpy/__init__.py)

[alex@felapk ~]$ python --version
Python 3.11.3

I installed via pip3

Thanks in advance!

**Comment by Rolf-Hempel** [comment]
Hi,

Thanks for your report! I fixed the problem and uploaded a new Version 0.9.7 to PyPI.

Best Wishes,
 Rolf
