### ISSUE TITLE
TypeError: 'numpy._DTypeMeta' object is not subscriptable

### ISSUE THREAD

**Issue by binary-stellar-system** [Rolf-Hempel/PlanetarySystemStacker#74]
Just installed on Ubuntu 22.04.3 and I get this stacktrace when I try to run. I had to add ~/.local/bin to path as it complained during install about that.  I used "pip install planetary-system-stacker" to install

Traceback (most recent call last):
  File "/home/joea/.local/bin/PlanetarySystemStacker", line 5, in <module>
    from planetary_system_stacker.planetary_system_stacker import main
  File "/home/joea/.local/lib/python3.10/site-packages/planetary_system_stacker/planetary_system_stacker.py", line 37, in <module>
    import cv2
  File "/home/joea/.local/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/joea/.local/lib/python3.10/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/joea/.local/lib/python3.10/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/joea/.local/lib/python3.10/site-packages/cv2/typing/__init__.py", line 69, in <module>
    NumPyArrayGeneric = numpy.ndarray[typing.Any, numpy.dtype[numpy.generic]]
TypeError: 'numpy._DTypeMeta' object is not subscriptable

**Comment by Rolf-Hempel** [comment]
This has nothing to do with PSS itself. It's a library incompatibility between the (very recent) libraries OpenCV and Numpy. You can avoid the problem by using an older version of Python and the libraries used by PSS. Here is the latest configuration I'm using:

![Python-Config](https://github.com/Rolf-Hempel/PlanetarySystemStacker/assets/19596791/bb9d4caa-c621-49e1-8fce-11753b8a734b)

PSS runs without problems with this configuration.
